**Problem 1**

Import Numpy as np

In [1]:

import numpy as np

**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [3]:
nums_1D = np.array([0,1,2,3,4,5,6,7,8,9])
print(nums_1D)


[0 1 2 3 4 5 6 7 8 9]


**Problem 3**

Create a 3×3 numpy array of all True’s.

In [13]:
nums_Arr2D = np.array([ [True, True, True], [True,True,True], [True,True, True]])
print(nums_Arr2D)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Problem 4**

Extract all odd numbers from arr.

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = arr % 2 != 0
arr_b = arr[mask]
print(arr_b)
mask1 = arr %2 == 0
arr_c = arr[mask1]
print(arr_c)
print(type(arr_b))

[1 3 5 7 9]
[0 2 4 6 8]
<class 'numpy.ndarray'>


**Problem 5**

Replace all odd numbers in arr with -1.

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#mask = arr % 2 != 0 
arr[arr%2!=0]=-1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [18]:
arr = np.arange(10)
arr1 = np.reshape(arr,(2,5))
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [46]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
a1 = a.reshape(5,2)
print(a1)
b1 = b.reshape(5,2)
print(b1)
#c = b.reshape(10,1)
#print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


**Problem 8**

Stack the arrays a and b horizontally.

In [47]:
print(a)
print(b)
np.hstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**Problem 9**

Get the common items between a and b.

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


**Problem 10**

From array a remove all items present in array b

In [54]:
a = np.array([1,2,3,4,5])
a1 = np.array([1,1,3,4,1])
b = np.array([5,6,7,8,9])
b1 = np.array([4,5,6,7,8,9])
res = np.setdiff1d(a,a1)
res1 = np.setdiff1d(a,b1)
print(res, res1)
print(np.setdiff1d(a,b))



[2 5] [1 2 3]
[1 2 3 4]


**Problem 11**

Get the positions where elements of a and b match

In [76]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.array([7,2,10,-2,7,4,9,4,9,8])
print(np.arange(len(a))[a==b])
print(np.arange(len(b))[b!=c])
print(np.arange(len(c))[a!=c])


[1 3 5 7]
[3]
[0 2 3 4 6 8 9]


**Problem 12** 

Get all items between 5 and 10 from a.

In [55]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.logical_and(a>5, a < 10)]

array([6, 9])

**Problem 13**

Swap columns 1 and 2 in the array arr.

In [67]:
arr = np.arange(9).reshape(3,3)
print(arr)
#print(arr[:,2])
#print(arr[1,:])
temp = np.copy(arr[:,0])
arr[:,0] = arr[:,1]
print(arr)
arr[:,1] = temp
print("sonuc\n",arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 2]
 [4 4 5]
 [7 7 8]]
sonuc
 [[1 0 2]
 [4 3 5]
 [7 6 8]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [71]:
arr = np.arange(9).reshape(3,3)
print(arr)
temp = np.copy(arr[1,:])
arr[1,:] = arr[2,:]
arr[2,:] = temp
print(arr)
arr1 = np.arange(9).reshape(3,3)
print(arr1)
np.flip([0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0])

**Problem 15**

Reverse the rows of a 2D array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)

**Problem 16**

Reverse the columns of a 2D array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)

**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.